/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, clang++ 16.0.0 -fPIC -O3) */

module mini(clk, d, q);
  input clk;
  wire clk;
  input d;
  wire d;
  output q;
  wire q;
  dff _0_ (
    .clk(clk),
    .d(d),
    .q(q)
  );
endmodule
