name: pyverilog-env
channels:
  - defaults
  - conda-forge
  - pytorch

dependencies:
  - python=3.9
  - iverilog
  - pip
  - numpy
  - networkx
  - jupyter
  - pytorch
  - torchvision
  - pip:
      - pyverilog
