/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "./Trojans/trojan1.v:1" *)
module Trojan1(clk, rst, r1, trigger);
  (* src = "./Trojans/trojan1.v:10" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "./Trojans/trojan1.v:2" *)
  input clk;
  (* src = "./Trojans/trojan1.v:8" *)
  reg [3:0] counter;
  (* src = "./Trojans/trojan1.v:4" *)
  input r1;
  (* src = "./Trojans/trojan1.v:3" *)
  input rst;
  (* src = "./Trojans/trojan1.v:5" *)
  output trigger;
  assign _01_ = rst & counter[0];
  assign _00_[0] = _01_ ^ r1;
  assign _02_ = counter[1] & rst;
  assign _03_ = _02_ ^ _01_;
  assign _00_[1] = r1 ? _03_ : _02_;
  assign _04_ = counter[2] & rst;
  assign _05_ = ~(_02_ & _01_);
  assign _06_ = ~(_05_ ^ _04_);
  assign _00_[2] = r1 ? _06_ : _04_;
  assign _07_ = counter[3] & rst;
  assign _08_ = _04_ & ~(_05_);
  assign _09_ = _08_ ^ _07_;
  assign _00_[3] = r1 ? _09_ : _07_;
  (* src = "./Trojans/trojan1.v:10" *)
  always @(posedge clk)
      counter[0] <= _00_[0];
  (* src = "./Trojans/trojan1.v:10" *)
  always @(posedge clk)
      counter[1] <= _00_[1];
  (* src = "./Trojans/trojan1.v:10" *)
  always @(posedge clk)
      counter[2] <= _00_[2];
  (* src = "./Trojans/trojan1.v:10" *)
  always @(posedge clk)
      counter[3] <= _00_[3];
  assign trigger = counter[3];
endmodule
