/* Generated by Yosys 0.51+107 (git sha1 f03b44959, g++ 14.2.1 -fPIC -O3) */

module Trojan1(clk, rst, r1, trigger);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input clk;
  wire clk;
  wire [3:0] counter;
  input r1;
  wire r1;
  input rst;
  wire rst;
  output trigger;
  wire trigger;
  \or  _11_ (
    .A(counter[0]),
    .B(rst),
    .Y(_01_)
  );
  \or  _12_ (
    .A(r1),
    .B(_01_),
    .Y(_02_)
  );
  \xor  _13_ (
    .A(r1),
    .B(_01_),
    .Y(_00_[0])
  );
  \or  _14_ (
    .A(rst),
    .B(counter[1]),
    .Y(_03_)
  );
  \and  _15_ (
    .A(_02_),
    .B(_03_),
    .Y(_04_)
  );
  \nand  _16_ (
    .A(counter[1]),
    .B(_02_),
    .Y(_05_)
  );
  \or  _17_ (
    .A(_04_),
    .B(_05_),
    .Y(_00_[1])
  );
  \nand  _18_ (
    .A(rst),
    .B(counter[2]),
    .Y(_06_)
  );
  \nor  _19_ (
    .A(_05_),
    .B(_06_),
    .Y(_07_)
  );
  \xor  _20_ (
    .A(_05_),
    .B(_06_),
    .Y(_00_[2])
  );
  \or  _21_ (
    .A(counter[3]),
    .B(_07_),
    .Y(_08_)
  );
  \or  _22_ (
    .A(rst),
    .B(counter[3]),
    .Y(_09_)
  );
  \nor  _23_ (
    .A(_07_),
    .B(_09_),
    .Y(_10_)
  );
  \nor  _24_ (
    .A(_08_),
    .B(_10_),
    .Y(_00_[3])
  );
  dff _25_ (
    .C(clk),
    .D(_00_[0]),
    .Q(counter[0])
  );
  dff _26_ (
    .C(clk),
    .D(_00_[1]),
    .Q(counter[1])
  );
  dff _27_ (
    .C(clk),
    .D(_00_[2]),
    .Q(counter[2])
  );
  dff _28_ (
    .C(clk),
    .D(_00_[3]),
    .Q(counter[3])
  );
  assign trigger = counter[3];
endmodule
