/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, clang++ 16.0.0 -fPIC -O3) */

module Trojan1(clk, rst, r1, trigger);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input clk;
  wire clk;
  wire [3:0] counter;
  input r1;
  wire r1;
  input rst;
  wire rst;
  output trigger;
  wire trigger;
  \not  _14_ (
    .A(counter[1]),
    .Y(_01_)
  );
  \and  _15_ (
    .A(counter[0]),
    .B(rst),
    .Y(_02_)
  );
  \nor  _16_ (
    .A(r1),
    .B(_02_),
    .Y(_03_)
  );
  \or  _17_ (
    .A(r1),
    .B(_02_),
    .Y(_04_)
  );
  \and  _18_ (
    .A(_03_),
    .B(_04_),
    .Y(_00_[0])
  );
  \nor  _19_ (
    .A(rst),
    .B(counter[1]),
    .Y(_05_)
  );
  \and  _20_ (
    .A(_03_),
    .B(_05_),
    .Y(_06_)
  );
  \nand  _21_ (
    .A(_01_),
    .B(_03_),
    .Y(_07_)
  );
  \nand  _22_ (
    .A(_06_),
    .B(_07_),
    .Y(_00_[1])
  );
  \and  _23_ (
    .A(rst),
    .B(counter[2]),
    .Y(_08_)
  );
  \nor  _24_ (
    .A(_07_),
    .B(_08_),
    .Y(_09_)
  );
  \or  _25_ (
    .A(_07_),
    .B(_08_),
    .Y(_10_)
  );
  \and  _26_ (
    .A(_09_),
    .B(_10_),
    .Y(_00_[2])
  );
  \and  _27_ (
    .A(rst),
    .B(counter[3]),
    .Y(_11_)
  );
  \or  _28_ (
    .A(counter[3]),
    .B(_09_),
    .Y(_12_)
  );
  \nor  _29_ (
    .A(_09_),
    .B(_11_),
    .Y(_13_)
  );
  \nor  _30_ (
    .A(_12_),
    .B(_13_),
    .Y(_00_[3])
  );
  dff _31_ (
    .C(clk),
    .D(_00_[0]),
    .Q(counter[0]),
    .RST(1'h0),
    .SET(1'h0)
  );
  dff _32_ (
    .C(clk),
    .D(_00_[1]),
    .Q(counter[1]),
    .RST(1'h0),
    .SET(1'h0)
  );
  dff _33_ (
    .C(clk),
    .D(_00_[2]),
    .Q(counter[2]),
    .RST(1'h0),
    .SET(1'h0)
  );
  dff _34_ (
    .C(clk),
    .D(_00_[3]),
    .Q(counter[3]),
    .RST(1'h0),
    .SET(1'h0)
  );
  assign trigger = counter[3];
endmodule
