/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, clang++ 16.0.0 -fPIC -O3) */

module Trojan2(clk, rst, data_in, force_reset);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  input clk;
  wire clk;
  input [7:0] data_in;
  wire [7:0] data_in;
  output force_reset;
  wire force_reset;
  wire [7:0] prev_data;
  input rst;
  wire rst;
  wire trigger;
  \nand  _14_ (
    .A(data_in[0]),
    .B(data_in[2]),
    .Y(_00_)
  );
  \nand  _15_ (
    .A(data_in[4]),
    .B(data_in[6]),
    .Y(_01_)
  );
  \and  _16_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  \nand  _17_ (
    .A(prev_data[1]),
    .B(prev_data[3]),
    .Y(_03_)
  );
  \nand  _18_ (
    .A(prev_data[5]),
    .B(prev_data[7]),
    .Y(_04_)
  );
  \and  _19_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  \and  _20_ (
    .A(_02_),
    .B(_05_),
    .Y(_06_)
  );
  \and  _21_ (
    .A(data_in[1]),
    .B(data_in[3]),
    .Y(_07_)
  );
  \and  _22_ (
    .A(data_in[5]),
    .B(data_in[7]),
    .Y(_08_)
  );
  \and  _23_ (
    .A(_07_),
    .B(_08_),
    .Y(_09_)
  );
  \and  _24_ (
    .A(prev_data[0]),
    .B(prev_data[2]),
    .Y(_10_)
  );
  \and  _25_ (
    .A(prev_data[4]),
    .B(prev_data[6]),
    .Y(_11_)
  );
  \and  _26_ (
    .A(_10_),
    .B(_11_),
    .Y(_12_)
  );
  \and  _27_ (
    .A(_09_),
    .B(_12_),
    .Y(_13_)
  );
  \nor  _28_ (
    .A(_06_),
    .B(_13_),
    .Y(trigger)
  );
  dff _29_ (
    .C(clk),
    .D(trigger),
    .Q(force_reset),
    .RST(rst),
    .SET(1'h0)
  );
  dff _30_ (
    .C(clk),
    .D(data_in[0]),
    .Q(prev_data[0]),
    .RST(rst),
    .SET(1'h0)
  );
  dff _31_ (
    .C(clk),
    .D(data_in[1]),
    .Q(prev_data[1]),
    .RST(rst),
    .SET(1'h0)
  );
  dff _32_ (
    .C(clk),
    .D(data_in[2]),
    .Q(prev_data[2]),
    .RST(rst),
    .SET(1'h0)
  );
  dff _33_ (
    .C(clk),
    .D(data_in[3]),
    .Q(prev_data[3]),
    .RST(rst),
    .SET(1'h0)
  );
  dff _34_ (
    .C(clk),
    .D(data_in[4]),
    .Q(prev_data[4]),
    .RST(rst),
    .SET(1'h0)
  );
  dff _35_ (
    .C(clk),
    .D(data_in[5]),
    .Q(prev_data[5]),
    .RST(rst),
    .SET(1'h0)
  );
  dff _36_ (
    .C(clk),
    .D(data_in[6]),
    .Q(prev_data[6]),
    .RST(rst),
    .SET(1'h0)
  );
  dff _37_ (
    .C(clk),
    .D(data_in[7]),
    .Q(prev_data[7]),
    .RST(rst),
    .SET(1'h0)
  );
endmodule
