/* Generated by Yosys 0.51+107 (git sha1 f03b44959, g++ 14.2.1 -fPIC -O3) */

module Trojan7(wb_addr_i, wb_data_i, s0_data_i, slv_sel);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  input [31:0] s0_data_i;
  wire [31:0] s0_data_i;
  output [3:0] slv_sel;
  wire [3:0] slv_sel;
  input [31:0] wb_addr_i;
  wire [31:0] wb_addr_i;
  input [31:0] wb_data_i;
  wire [31:0] wb_data_i;
  \nand  _063_ (
    .A(s0_data_i[9]),
    .B(s0_data_i[12]),
    .Y(_036_)
  );
  \nand  _064_ (
    .A(wb_data_i[29]),
    .B(s0_data_i[5]),
    .Y(_037_)
  );
  \and  _065_ (
    .A(_036_),
    .B(_037_),
    .Y(_038_)
  );
  \nand  _066_ (
    .A(s0_data_i[25]),
    .B(s0_data_i[28]),
    .Y(_039_)
  );
  \nand  _067_ (
    .A(s0_data_i[18]),
    .B(s0_data_i[20]),
    .Y(_040_)
  );
  \and  _068_ (
    .A(_039_),
    .B(_040_),
    .Y(_041_)
  );
  \and  _069_ (
    .A(_038_),
    .B(_041_),
    .Y(_042_)
  );
  \nand  _070_ (
    .A(wb_data_i[11]),
    .B(wb_data_i[15]),
    .Y(_043_)
  );
  \nand  _071_ (
    .A(wb_data_i[6]),
    .B(wb_data_i[7]),
    .Y(_044_)
  );
  \and  _072_ (
    .A(_043_),
    .B(_044_),
    .Y(_045_)
  );
  \nand  _073_ (
    .A(wb_data_i[17]),
    .B(wb_data_i[21]),
    .Y(_046_)
  );
  \nand  _074_ (
    .A(wb_data_i[23]),
    .B(wb_data_i[25]),
    .Y(_047_)
  );
  \and  _075_ (
    .A(_046_),
    .B(_047_),
    .Y(_048_)
  );
  \and  _076_ (
    .A(_045_),
    .B(_048_),
    .Y(_049_)
  );
  \and  _077_ (
    .A(_042_),
    .B(_049_),
    .Y(_050_)
  );
  \and  _078_ (
    .A(s0_data_i[10]),
    .B(s0_data_i[15]),
    .Y(_051_)
  );
  \and  _079_ (
    .A(s0_data_i[4]),
    .B(s0_data_i[6]),
    .Y(_052_)
  );
  \and  _080_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  \and  _081_ (
    .A(s0_data_i[29]),
    .B(s0_data_i[30]),
    .Y(_054_)
  );
  \and  _082_ (
    .A(s0_data_i[17]),
    .B(s0_data_i[23]),
    .Y(_055_)
  );
  \and  _083_ (
    .A(_054_),
    .B(_055_),
    .Y(_056_)
  );
  \and  _084_ (
    .A(_053_),
    .B(_056_),
    .Y(_057_)
  );
  \and  _085_ (
    .A(wb_data_i[8]),
    .B(wb_data_i[9]),
    .Y(_058_)
  );
  \and  _086_ (
    .A(wb_data_i[0]),
    .B(wb_data_i[3]),
    .Y(_059_)
  );
  \and  _087_ (
    .A(_058_),
    .B(_059_),
    .Y(_060_)
  );
  \and  _088_ (
    .A(wb_data_i[28]),
    .B(s0_data_i[0]),
    .Y(_061_)
  );
  \and  _089_ (
    .A(wb_data_i[18]),
    .B(wb_data_i[24]),
    .Y(_062_)
  );
  \and  _090_ (
    .A(_061_),
    .B(_062_),
    .Y(_000_)
  );
  \and  _091_ (
    .A(_060_),
    .B(_000_),
    .Y(_001_)
  );
  \and  _092_ (
    .A(_057_),
    .B(_001_),
    .Y(_002_)
  );
  \and  _093_ (
    .A(_050_),
    .B(_002_),
    .Y(_003_)
  );
  \nand  _094_ (
    .A(s0_data_i[7]),
    .B(s0_data_i[14]),
    .Y(_004_)
  );
  \nand  _095_ (
    .A(s0_data_i[2]),
    .B(s0_data_i[3]),
    .Y(_005_)
  );
  \and  _096_ (
    .A(_004_),
    .B(_005_),
    .Y(_006_)
  );
  \nand  _097_ (
    .A(s0_data_i[26]),
    .B(s0_data_i[27]),
    .Y(_007_)
  );
  \nand  _098_ (
    .A(s0_data_i[16]),
    .B(s0_data_i[22]),
    .Y(_008_)
  );
  \and  _099_ (
    .A(_007_),
    .B(_008_),
    .Y(_009_)
  );
  \and  _100_ (
    .A(_006_),
    .B(_009_),
    .Y(_010_)
  );
  \nand  _101_ (
    .A(wb_data_i[12]),
    .B(wb_data_i[13]),
    .Y(_011_)
  );
  \nand  _102_ (
    .A(wb_data_i[5]),
    .B(wb_data_i[10]),
    .Y(_012_)
  );
  \and  _103_ (
    .A(_011_),
    .B(_012_),
    .Y(_013_)
  );
  \nand  _104_ (
    .A(wb_data_i[19]),
    .B(wb_data_i[20]),
    .Y(_014_)
  );
  \nand  _105_ (
    .A(wb_data_i[22]),
    .B(wb_data_i[27]),
    .Y(_015_)
  );
  \and  _106_ (
    .A(_014_),
    .B(_015_),
    .Y(_016_)
  );
  \and  _107_ (
    .A(_013_),
    .B(_016_),
    .Y(_017_)
  );
  \and  _108_ (
    .A(_010_),
    .B(_017_),
    .Y(_018_)
  );
  \and  _109_ (
    .A(s0_data_i[11]),
    .B(s0_data_i[13]),
    .Y(_019_)
  );
  \and  _110_ (
    .A(s0_data_i[1]),
    .B(s0_data_i[8]),
    .Y(_020_)
  );
  \and  _111_ (
    .A(_019_),
    .B(_020_),
    .Y(_021_)
  );
  \and  _112_ (
    .A(s0_data_i[24]),
    .B(s0_data_i[31]),
    .Y(_022_)
  );
  \and  _113_ (
    .A(s0_data_i[19]),
    .B(s0_data_i[21]),
    .Y(_023_)
  );
  \and  _114_ (
    .A(_022_),
    .B(_023_),
    .Y(_024_)
  );
  \and  _115_ (
    .A(_021_),
    .B(_024_),
    .Y(_025_)
  );
  \and  _116_ (
    .A(wb_data_i[4]),
    .B(wb_data_i[14]),
    .Y(_026_)
  );
  \and  _117_ (
    .A(wb_data_i[1]),
    .B(wb_data_i[2]),
    .Y(_027_)
  );
  \and  _118_ (
    .A(_026_),
    .B(_027_),
    .Y(_028_)
  );
  \and  _119_ (
    .A(wb_data_i[30]),
    .B(wb_data_i[31]),
    .Y(_029_)
  );
  \and  _120_ (
    .A(wb_data_i[16]),
    .B(wb_data_i[26]),
    .Y(_030_)
  );
  \and  _121_ (
    .A(_029_),
    .B(_030_),
    .Y(_031_)
  );
  \and  _122_ (
    .A(_028_),
    .B(_031_),
    .Y(_032_)
  );
  \and  _123_ (
    .A(_025_),
    .B(_032_),
    .Y(_033_)
  );
  \and  _124_ (
    .A(_018_),
    .B(_033_),
    .Y(_034_)
  );
  \nor  _125_ (
    .A(_003_),
    .B(_034_),
    .Y(_035_)
  );
  \xor  _126_ (
    .A(wb_addr_i[28]),
    .B(_035_),
    .Y(slv_sel[0])
  );
  \xor  _127_ (
    .A(wb_addr_i[29]),
    .B(_035_),
    .Y(slv_sel[1])
  );
  \xor  _128_ (
    .A(wb_addr_i[30]),
    .B(_035_),
    .Y(slv_sel[2])
  );
  \xor  _129_ (
    .A(wb_addr_i[31]),
    .B(_035_),
    .Y(slv_sel[3])
  );
endmodule
