/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, clang++ 16.0.0 -fPIC -O3) */

module Trojan3(clk, rst, data_in, data_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  input clk;
  wire clk;
  wire counter[0] ;
  wire counter[1] ;
  wire counter[2] ;
  wire counter[3] ;
  wire counter[4] ;
  wire counter[5] ;
  wire counter[6] ;
  wire counter[7] ;
  input [15:0] data_in;
  wire [15:0] data_in;
  output [15:0] data_out;
  wire [15:0] data_out;
  input rst;
  wire rst;
  not  _157_ (
    .A(counter[0] ),
    .Y(_015_)
  );
  not  _158_ (
    .A(data_in[1]),
    .Y(_111_)
  );
  and  _159_ (
    .A(counter[1] ),
    .B(counter[0] ),
    .Y(_112_)
  );
  and  _160_ (
    .A(counter[3] ),
    .B(counter[2] ),
    .Y(_113_)
  );
  and  _161_ (
    .A(_113_),
    .B(_112_),
    .Y(_114_)
  );
  and  _162_ (
    .A(counter[5] ),
    .B(counter[4] ),
    .Y(_115_)
  );
  and  _163_ (
    .A(counter[6] ),
    .B(counter[7] ),
    .Y(_116_)
  );
  and  _164_ (
    .A(_116_),
    .B(_115_),
    .Y(_117_)
  );
  and  _165_ (
    .A(_117_),
    .B(_114_),
    .Y(_118_)
  );
  and  _166_ (
    .A(_118_),
    .B(_111_),
    .Y(_119_)
  );
  nand  _167_ (
    .A(_118_),
    .B(_111_),
    .Y(_120_)
  );
  or  _168_ (
    .A(_120_),
    .B(_119_),
    .Y(_006_)
  );
  nand  _169_ (
    .A(data_in[2]),
    .B(_111_),
    .Y(_121_)
  );
  and  _170_ (
    .A(data_in[2]),
    .B(_111_),
    .Y(_122_)
  );
  or  _171_ (
    .A(_122_),
    .B(_121_),
    .Y(_123_)
  );
  and  _172_ (
    .A(_123_),
    .B(_118_),
    .Y(_124_)
  );
  not  _173_ (
    .A(_118_),
    .Y(_125_)
  );
  and  _174_ (
    .A(_125_),
    .B(data_in[2]),
    .Y(_126_)
  );
  or  _175_ (
    .A(_126_),
    .B(_124_),
    .Y(_007_)
  );
  and  _176_ (
    .A(data_in[2]),
    .B(data_in[1]),
    .Y(_127_)
  );
  not  _177_ (
    .A(_127_),
    .Y(_128_)
  );
  nand  _178_ (
    .A(_128_),
    .B(data_in[3]),
    .Y(_129_)
  );
  and  _179_ (
    .A(_128_),
    .B(data_in[3]),
    .Y(_130_)
  );
  or  _180_ (
    .A(_130_),
    .B(_129_),
    .Y(_131_)
  );
  and  _181_ (
    .A(_131_),
    .B(_118_),
    .Y(_132_)
  );
  and  _182_ (
    .A(_125_),
    .B(data_in[3]),
    .Y(_133_)
  );
  or  _183_ (
    .A(_133_),
    .B(_132_),
    .Y(_008_)
  );
  not  _184_ (
    .A(data_in[4]),
    .Y(_134_)
  );
  and  _185_ (
    .A(data_in[3]),
    .B(data_in[2]),
    .Y(_135_)
  );
  and  _186_ (
    .A(_135_),
    .B(data_in[1]),
    .Y(_136_)
  );
  and  _187_ (
    .A(_136_),
    .B(_134_),
    .Y(_137_)
  );
  nand  _188_ (
    .A(_136_),
    .B(_134_),
    .Y(_138_)
  );
  or  _189_ (
    .A(_138_),
    .B(_137_),
    .Y(_139_)
  );
  and  _190_ (
    .A(_139_),
    .B(_118_),
    .Y(_140_)
  );
  nand  _191_ (
    .A(_118_),
    .B(_134_),
    .Y(_141_)
  );
  or  _192_ (
    .A(_141_),
    .B(_140_),
    .Y(_009_)
  );
  nor  _193_ (
    .A(_136_),
    .B(data_in[4]),
    .Y(_142_)
  );
  nand  _194_ (
    .A(_142_),
    .B(data_in[5]),
    .Y(_143_)
  );
  and  _195_ (
    .A(_142_),
    .B(data_in[5]),
    .Y(_144_)
  );
  or  _196_ (
    .A(_144_),
    .B(_143_),
    .Y(_145_)
  );
  and  _197_ (
    .A(_145_),
    .B(_118_),
    .Y(_146_)
  );
  and  _198_ (
    .A(_125_),
    .B(data_in[5]),
    .Y(_147_)
  );
  or  _199_ (
    .A(_147_),
    .B(_146_),
    .Y(_010_)
  );
  not  _200_ (
    .A(data_in[6]),
    .Y(_148_)
  );
  and  _201_ (
    .A(data_in[5]),
    .B(data_in[4]),
    .Y(_149_)
  );
  and  _202_ (
    .A(_149_),
    .B(_136_),
    .Y(_150_)
  );
  and  _203_ (
    .A(_150_),
    .B(_148_),
    .Y(_151_)
  );
  nand  _204_ (
    .A(_150_),
    .B(_148_),
    .Y(_152_)
  );
  or  _205_ (
    .A(_152_),
    .B(_151_),
    .Y(_153_)
  );
  and  _206_ (
    .A(_153_),
    .B(_118_),
    .Y(_154_)
  );
  nand  _207_ (
    .A(_118_),
    .B(_148_),
    .Y(_155_)
  );
  or  _208_ (
    .A(_155_),
    .B(_154_),
    .Y(_011_)
  );
  nor  _209_ (
    .A(_150_),
    .B(data_in[6]),
    .Y(_156_)
  );
  nand  _210_ (
    .A(_156_),
    .B(data_in[7]),
    .Y(_023_)
  );
  and  _211_ (
    .A(_156_),
    .B(data_in[7]),
    .Y(_024_)
  );
  or  _212_ (
    .A(_024_),
    .B(_023_),
    .Y(_025_)
  );
  and  _213_ (
    .A(_025_),
    .B(_118_),
    .Y(_026_)
  );
  and  _214_ (
    .A(_125_),
    .B(data_in[7]),
    .Y(_027_)
  );
  or  _215_ (
    .A(_027_),
    .B(_026_),
    .Y(_012_)
  );
  not  _216_ (
    .A(data_in[8]),
    .Y(_028_)
  );
  and  _217_ (
    .A(data_in[7]),
    .B(data_in[6]),
    .Y(_029_)
  );
  and  _218_ (
    .A(_029_),
    .B(_149_),
    .Y(_030_)
  );
  and  _219_ (
    .A(_030_),
    .B(_136_),
    .Y(_031_)
  );
  and  _220_ (
    .A(_031_),
    .B(_028_),
    .Y(_032_)
  );
  nor  _221_ (
    .A(_030_),
    .B(_136_),
    .Y(_033_)
  );
  and  _222_ (
    .A(_033_),
    .B(data_in[8]),
    .Y(_034_)
  );
  or  _223_ (
    .A(_034_),
    .B(_032_),
    .Y(_035_)
  );
  and  _224_ (
    .A(_035_),
    .B(_118_),
    .Y(_036_)
  );
  nand  _225_ (
    .A(_118_),
    .B(_028_),
    .Y(_037_)
  );
  or  _226_ (
    .A(_037_),
    .B(_036_),
    .Y(_013_)
  );
  or  _227_ (
    .A(_033_),
    .B(_028_),
    .Y(_038_)
  );
  nand  _228_ (
    .A(_038_),
    .B(data_in[9]),
    .Y(_039_)
  );
  and  _229_ (
    .A(_038_),
    .B(data_in[9]),
    .Y(_040_)
  );
  or  _230_ (
    .A(_040_),
    .B(_039_),
    .Y(_041_)
  );
  and  _231_ (
    .A(_041_),
    .B(_118_),
    .Y(_042_)
  );
  and  _232_ (
    .A(_125_),
    .B(data_in[9]),
    .Y(_043_)
  );
  or  _233_ (
    .A(_043_),
    .B(_042_),
    .Y(_014_)
  );
  and  _234_ (
    .A(data_in[9]),
    .B(data_in[8]),
    .Y(_044_)
  );
  nor  _235_ (
    .A(_044_),
    .B(_031_),
    .Y(_045_)
  );
  nand  _236_ (
    .A(_045_),
    .B(data_in[10]),
    .Y(_046_)
  );
  and  _237_ (
    .A(_045_),
    .B(data_in[10]),
    .Y(_047_)
  );
  or  _238_ (
    .A(_047_),
    .B(_046_),
    .Y(_048_)
  );
  and  _239_ (
    .A(_048_),
    .B(_118_),
    .Y(_049_)
  );
  not  _240_ (
    .A(data_in[10]),
    .Y(_050_)
  );
  nand  _241_ (
    .A(_118_),
    .B(_050_),
    .Y(_051_)
  );
  or  _242_ (
    .A(_051_),
    .B(_049_),
    .Y(_000_)
  );
  or  _243_ (
    .A(_045_),
    .B(_050_),
    .Y(_052_)
  );
  nand  _244_ (
    .A(_052_),
    .B(data_in[11]),
    .Y(_053_)
  );
  and  _245_ (
    .A(_052_),
    .B(data_in[11]),
    .Y(_054_)
  );
  or  _246_ (
    .A(_054_),
    .B(_053_),
    .Y(_055_)
  );
  and  _247_ (
    .A(_055_),
    .B(_118_),
    .Y(_056_)
  );
  and  _248_ (
    .A(_125_),
    .B(data_in[11]),
    .Y(_057_)
  );
  or  _249_ (
    .A(_057_),
    .B(_056_),
    .Y(_001_)
  );
  not  _250_ (
    .A(data_in[12]),
    .Y(_058_)
  );
  and  _251_ (
    .A(data_in[11]),
    .B(data_in[10]),
    .Y(_059_)
  );
  and  _252_ (
    .A(_059_),
    .B(_044_),
    .Y(_060_)
  );
  and  _253_ (
    .A(_060_),
    .B(_031_),
    .Y(_061_)
  );
  and  _254_ (
    .A(_061_),
    .B(_058_),
    .Y(_062_)
  );
  nor  _255_ (
    .A(_060_),
    .B(_031_),
    .Y(_063_)
  );
  and  _256_ (
    .A(_063_),
    .B(data_in[12]),
    .Y(_064_)
  );
  or  _257_ (
    .A(_064_),
    .B(_062_),
    .Y(_065_)
  );
  and  _258_ (
    .A(_065_),
    .B(_118_),
    .Y(_066_)
  );
  nand  _259_ (
    .A(_118_),
    .B(_058_),
    .Y(_067_)
  );
  or  _260_ (
    .A(_067_),
    .B(_066_),
    .Y(_002_)
  );
  or  _261_ (
    .A(_063_),
    .B(_058_),
    .Y(_068_)
  );
  nand  _262_ (
    .A(_068_),
    .B(data_in[13]),
    .Y(_069_)
  );
  and  _263_ (
    .A(_068_),
    .B(data_in[13]),
    .Y(_070_)
  );
  or  _264_ (
    .A(_070_),
    .B(_069_),
    .Y(_071_)
  );
  and  _265_ (
    .A(_071_),
    .B(_118_),
    .Y(_072_)
  );
  and  _266_ (
    .A(_125_),
    .B(data_in[13]),
    .Y(_073_)
  );
  or  _267_ (
    .A(_073_),
    .B(_072_),
    .Y(_003_)
  );
  and  _268_ (
    .A(data_in[13]),
    .B(data_in[12]),
    .Y(_074_)
  );
  nor  _269_ (
    .A(_074_),
    .B(_061_),
    .Y(_075_)
  );
  nand  _270_ (
    .A(_075_),
    .B(data_in[14]),
    .Y(_076_)
  );
  and  _271_ (
    .A(_075_),
    .B(data_in[14]),
    .Y(_077_)
  );
  or  _272_ (
    .A(_077_),
    .B(_076_),
    .Y(_078_)
  );
  and  _273_ (
    .A(_078_),
    .B(_118_),
    .Y(_079_)
  );
  not  _274_ (
    .A(data_in[14]),
    .Y(_080_)
  );
  nand  _275_ (
    .A(_118_),
    .B(_080_),
    .Y(_081_)
  );
  or  _276_ (
    .A(_081_),
    .B(_079_),
    .Y(_004_)
  );
  or  _277_ (
    .A(_075_),
    .B(_080_),
    .Y(_082_)
  );
  nand  _278_ (
    .A(_082_),
    .B(data_in[15]),
    .Y(_083_)
  );
  and  _279_ (
    .A(_082_),
    .B(data_in[15]),
    .Y(_084_)
  );
  or  _280_ (
    .A(_084_),
    .B(_083_),
    .Y(_085_)
  );
  and  _281_ (
    .A(_085_),
    .B(_118_),
    .Y(_086_)
  );
  and  _282_ (
    .A(_125_),
    .B(data_in[15]),
    .Y(_087_)
  );
  or  _283_ (
    .A(_087_),
    .B(_086_),
    .Y(_005_)
  );
  nand  _284_ (
    .A(counter[1] ),
    .B(_015_),
    .Y(_088_)
  );
  and  _285_ (
    .A(counter[1] ),
    .B(_015_),
    .Y(_089_)
  );
  or  _286_ (
    .A(_089_),
    .B(_088_),
    .Y(_016_)
  );
  not  _287_ (
    .A(_112_),
    .Y(_090_)
  );
  nand  _288_ (
    .A(_090_),
    .B(counter[2] ),
    .Y(_091_)
  );
  and  _289_ (
    .A(_090_),
    .B(counter[2] ),
    .Y(_092_)
  );
  or  _290_ (
    .A(_092_),
    .B(_091_),
    .Y(_017_)
  );
  and  _291_ (
    .A(_112_),
    .B(counter[2] ),
    .Y(_093_)
  );
  not  _292_ (
    .A(_093_),
    .Y(_094_)
  );
  nand  _293_ (
    .A(_094_),
    .B(counter[3] ),
    .Y(_095_)
  );
  and  _294_ (
    .A(_094_),
    .B(counter[3] ),
    .Y(_096_)
  );
  or  _295_ (
    .A(_096_),
    .B(_095_),
    .Y(_018_)
  );
  not  _296_ (
    .A(_114_),
    .Y(_097_)
  );
  nand  _297_ (
    .A(_097_),
    .B(counter[4] ),
    .Y(_098_)
  );
  and  _298_ (
    .A(_097_),
    .B(counter[4] ),
    .Y(_099_)
  );
  or  _299_ (
    .A(_099_),
    .B(_098_),
    .Y(_019_)
  );
  and  _300_ (
    .A(_114_),
    .B(counter[4] ),
    .Y(_100_)
  );
  not  _301_ (
    .A(_100_),
    .Y(_101_)
  );
  nand  _302_ (
    .A(_101_),
    .B(counter[5] ),
    .Y(_102_)
  );
  and  _303_ (
    .A(_101_),
    .B(counter[5] ),
    .Y(_103_)
  );
  or  _304_ (
    .A(_103_),
    .B(_102_),
    .Y(_020_)
  );
  not  _305_ (
    .A(counter[6] ),
    .Y(_104_)
  );
  and  _306_ (
    .A(_115_),
    .B(_114_),
    .Y(_105_)
  );
  and  _307_ (
    .A(_105_),
    .B(_104_),
    .Y(_106_)
  );
  nand  _308_ (
    .A(_105_),
    .B(_104_),
    .Y(_107_)
  );
  or  _309_ (
    .A(_107_),
    .B(_106_),
    .Y(_021_)
  );
  nor  _310_ (
    .A(_105_),
    .B(counter[6] ),
    .Y(_108_)
  );
  nand  _311_ (
    .A(_108_),
    .B(counter[7] ),
    .Y(_109_)
  );
  and  _312_ (
    .A(_108_),
    .B(counter[7] ),
    .Y(_110_)
  );
  or  _313_ (
    .A(_110_),
    .B(_109_),
    .Y(_022_)
  );
  $_ALDFF_PP_  data_out_reg[0]  /* _314_ */ (
    .AD(data_in[0]),
    .C(clk),
    .D(data_in[0]),
    .L(rst),
    .Q(data_out[0])
  );
  $_ALDFF_PP_  data_out_reg[1]  /* _315_ */ (
    .AD(data_in[1]),
    .C(clk),
    .D(_006_),
    .L(rst),
    .Q(data_out[1])
  );
  $_ALDFF_PP_  data_out_reg[2]  /* _316_ */ (
    .AD(data_in[2]),
    .C(clk),
    .D(_007_),
    .L(rst),
    .Q(data_out[2])
  );
  $_ALDFF_PP_  data_out_reg[3]  /* _317_ */ (
    .AD(data_in[3]),
    .C(clk),
    .D(_008_),
    .L(rst),
    .Q(data_out[3])
  );
  $_ALDFF_PP_  data_out_reg[4]  /* _318_ */ (
    .AD(data_in[4]),
    .C(clk),
    .D(_009_),
    .L(rst),
    .Q(data_out[4])
  );
  $_ALDFF_PP_  data_out_reg[5]  /* _319_ */ (
    .AD(data_in[5]),
    .C(clk),
    .D(_010_),
    .L(rst),
    .Q(data_out[5])
  );
  $_ALDFF_PP_  data_out_reg[6]  /* _320_ */ (
    .AD(data_in[6]),
    .C(clk),
    .D(_011_),
    .L(rst),
    .Q(data_out[6])
  );
  $_ALDFF_PP_  data_out_reg[7]  /* _321_ */ (
    .AD(data_in[7]),
    .C(clk),
    .D(_012_),
    .L(rst),
    .Q(data_out[7])
  );
  $_ALDFF_PP_  data_out_reg[8]  /* _322_ */ (
    .AD(data_in[8]),
    .C(clk),
    .D(_013_),
    .L(rst),
    .Q(data_out[8])
  );
  $_ALDFF_PP_  data_out_reg[9]  /* _323_ */ (
    .AD(data_in[9]),
    .C(clk),
    .D(_014_),
    .L(rst),
    .Q(data_out[9])
  );
  $_ALDFF_PP_  data_out_reg[10]  /* _324_ */ (
    .AD(data_in[10]),
    .C(clk),
    .D(_000_),
    .L(rst),
    .Q(data_out[10])
  );
  $_ALDFF_PP_  data_out_reg[11]  /* _325_ */ (
    .AD(data_in[11]),
    .C(clk),
    .D(_001_),
    .L(rst),
    .Q(data_out[11])
  );
  $_ALDFF_PP_  data_out_reg[12]  /* _326_ */ (
    .AD(data_in[12]),
    .C(clk),
    .D(_002_),
    .L(rst),
    .Q(data_out[12])
  );
  $_ALDFF_PP_  data_out_reg[13]  /* _327_ */ (
    .AD(data_in[13]),
    .C(clk),
    .D(_003_),
    .L(rst),
    .Q(data_out[13])
  );
  $_ALDFF_PP_  data_out_reg[14]  /* _328_ */ (
    .AD(data_in[14]),
    .C(clk),
    .D(_004_),
    .L(rst),
    .Q(data_out[14])
  );
  $_ALDFF_PP_  data_out_reg[15]  /* _329_ */ (
    .AD(data_in[15]),
    .C(clk),
    .D(_005_),
    .L(rst),
    .Q(data_out[15])
  );
  dff _330_ (
    .C(clk),
    .D(_015_),
    .Q(counter[0] ),
    .RST(rst),
    .SET(1'b0)
  );
  dff _331_ (
    .C(clk),
    .D(_016_),
    .Q(counter[1] ),
    .RST(rst),
    .SET(1'b0)
  );
  dff _332_ (
    .C(clk),
    .D(_017_),
    .Q(counter[2] ),
    .RST(rst),
    .SET(1'b0)
  );
  dff _333_ (
    .C(clk),
    .D(_018_),
    .Q(counter[3] ),
    .RST(rst),
    .SET(1'b0)
  );
  dff _334_ (
    .C(clk),
    .D(_019_),
    .Q(counter[4] ),
    .RST(rst),
    .SET(1'b0)
  );
  dff _335_ (
    .C(clk),
    .D(_020_),
    .Q(counter[5] ),
    .RST(rst),
    .SET(1'b0)
  );
  dff _336_ (
    .C(clk),
    .D(_021_),
    .Q(counter[6] ),
    .RST(rst),
    .SET(1'b0)
  );
  dff _337_ (
    .C(clk),
    .D(_022_),
    .Q(counter[7] ),
    .RST(rst),
    .SET(1'b0)
  );
endmodule
