/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, clang++ 16.0.0 -fPIC -O3) */

module Trojan1(clk, rst, r1, trigger);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  input clk;
  wire clk;
  wire counter[0] ;
  wire counter[1] ;
  wire counter[2] ;
  input r1;
  wire r1;
  input rst;
  wire rst;
  output trigger;
  wire trigger;
  not  _31_ (
    .A(r1),
    .Y(_04_)
  );
  and  _32_ (
    .A(rst),
    .B(counter[0] ),
    .Y(_05_)
  );
  and  _33_ (
    .A(_05_),
    .B(_04_),
    .Y(_06_)
  );
  nor  _34_ (
    .A(rst),
    .B(counter[0] ),
    .Y(_07_)
  );
  and  _35_ (
    .A(_07_),
    .B(r1),
    .Y(_08_)
  );
  or  _36_ (
    .A(_08_),
    .B(_06_),
    .Y(_00_)
  );
  and  _37_ (
    .A(counter[1] ),
    .B(rst),
    .Y(_09_)
  );
  and  _38_ (
    .A(_09_),
    .B(_04_),
    .Y(_10_)
  );
  nor  _39_ (
    .A(counter[1] ),
    .B(rst),
    .Y(_11_)
  );
  and  _40_ (
    .A(_11_),
    .B(_05_),
    .Y(_12_)
  );
  and  _41_ (
    .A(_09_),
    .B(_07_),
    .Y(_13_)
  );
  or  _42_ (
    .A(_13_),
    .B(_12_),
    .Y(_14_)
  );
  and  _43_ (
    .A(_14_),
    .B(r1),
    .Y(_15_)
  );
  or  _44_ (
    .A(_15_),
    .B(_10_),
    .Y(_01_)
  );
  nor  _45_ (
    .A(counter[2] ),
    .B(rst),
    .Y(_16_)
  );
  nand  _46_ (
    .A(_16_),
    .B(r1),
    .Y(_17_)
  );
  not  _47_ (
    .A(_16_),
    .Y(_18_)
  );
  or  _48_ (
    .A(_11_),
    .B(_07_),
    .Y(_19_)
  );
  nand  _49_ (
    .A(_19_),
    .B(_18_),
    .Y(_20_)
  );
  and  _50_ (
    .A(_19_),
    .B(_18_),
    .Y(_21_)
  );
  or  _51_ (
    .A(_21_),
    .B(_20_),
    .Y(_22_)
  );
  and  _52_ (
    .A(_22_),
    .B(r1),
    .Y(_23_)
  );
  or  _53_ (
    .A(_23_),
    .B(_17_),
    .Y(_02_)
  );
  and  _54_ (
    .A(trigger),
    .B(rst),
    .Y(_24_)
  );
  and  _55_ (
    .A(_24_),
    .B(_04_),
    .Y(_25_)
  );
  or  _56_ (
    .A(_19_),
    .B(_16_),
    .Y(_26_)
  );
  nand  _57_ (
    .A(_26_),
    .B(_24_),
    .Y(_27_)
  );
  and  _58_ (
    .A(_26_),
    .B(_24_),
    .Y(_28_)
  );
  or  _59_ (
    .A(_28_),
    .B(_27_),
    .Y(_29_)
  );
  and  _60_ (
    .A(_29_),
    .B(r1),
    .Y(_30_)
  );
  or  _61_ (
    .A(_30_),
    .B(_25_),
    .Y(_03_)
  );
  dff _62_ (
    .C(clk),
    .D(_00_),
    .Q(counter[0] ),
    .RST(1'b0),
    .SET(1'b0)
  );
  dff _63_ (
    .C(clk),
    .D(_01_),
    .Q(counter[1] ),
    .RST(1'b0),
    .SET(1'b0)
  );
  dff _64_ (
    .C(clk),
    .D(_02_),
    .Q(counter[2] ),
    .RST(1'b0),
    .SET(1'b0)
  );
  dff _65_ (
    .C(clk),
    .D(_03_),
    .Q(trigger),
    .RST(1'b0),
    .SET(1'b0)
  );
endmodule
