/* Generated by Yosys 0.51+107 (git sha1 f03b44959, g++ 14.2.1 -fPIC -O3) */

module counter(clk, rst, en, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  input clk;
  wire clk;
  output [1:0] count;
  wire [1:0] count;
  input en;
  wire en;
  input rst;
  wire rst;
  \not  _11_ (
    .A(count[1]),
    .Y(_08_)
  );
  \not  _12_ (
    .A(rst),
    .Y(_09_)
  );
  \nand  _13_ (
    .A(en),
    .B(count[0]),
    .Y(_10_)
  );
  \nor  _14_ (
    .A(en),
    .B(count[0]),
    .Y(_02_)
  );
  \nor  _15_ (
    .A(rst),
    .B(_02_),
    .Y(_03_)
  );
  \nand  _16_ (
    .A(_10_),
    .B(_03_),
    .Y(_04_)
  );
  \not  _17_ (
    .A(_04_),
    .Y(_00_)
  );
  \nor  _18_ (
    .A(_08_),
    .B(_10_),
    .Y(_05_)
  );
  \nand  _19_ (
    .A(_08_),
    .B(_10_),
    .Y(_06_)
  );
  \nand  _20_ (
    .A(_09_),
    .B(_06_),
    .Y(_07_)
  );
  \nor  _21_ (
    .A(_05_),
    .B(_07_),
    .Y(_01_)
  );
  dff _22_ (
    .C(clk),
    .D(_00_),
    .Q(count[0])
  );
  dff _23_ (
    .C(clk),
    .D(_01_),
    .Q(count[1])
  );
endmodule
